// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Role struct {
	ID             interface{}
	Endpoint       string
	Operation      string
	BucketSize     int64
	AddTokenPerSec int64
	InitialTokens  int64
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}
