// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package role

import (
	"database/sql"
)

type RateLimiter struct {
	ID          int64
	Name        string
	Destination string
	DeletedAt   sql.NullTime
}

type Role struct {
	ID             int64
	Endpoint       string
	Operation      string
	BucketSize     int64
	AddTokenPerMin int64
	InitialTokens  int64
	DeletedAt      sql.NullTime
	RateLimiterID  int64
}
