// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package role

import (
	"database/sql"
	"time"
)

type RateLimiter struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Role struct {
	ID             int64
	Endpoint       string
	Operation      string
	BucketSize     int64
	CreatedAt      time.Time
	AddTokenPerMin int64
	InitialTokens  int64
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	RateLimiterID  int64
}
